apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: C:\Users\victo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o kube
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  serviceName: mongodb
  selector:
    matchLabels:
      io.kompose.service: mongodb
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\victo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o kube
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: mongodb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: doe
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: johndoe
            - name: MONGO_INITDB_ROOT_USERNAME
              value: john
          envFrom:
            - configMapRef:
                name: env
          image: mongodb/mongodb-community-server:7.0.23-ubi9
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          name: td6-mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /data/db
              name: td6-db-data
      volumes:
        - name: td6-db-data
          persistentVolumeClaim:
            claimName: td6-db-data
      restartPolicy: Always
