apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\victo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o kube
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapp
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\victo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o kube
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: webapp
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: webapp-2:latest
          imagePullPolicy: IfNotPresent
          name: td6-webapp
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
      restartPolicy: Always
