apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\victo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o kube
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 32080
  selector:
    io.kompose.service: webapp
